"""Add email field to resume

Revision ID: 94587e0b5a42
Revises: bd9c37f257a3
Create Date: 2025-07-19 11:32:08.119675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94587e0b5a42'
down_revision = 'bd9c37f257a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
