"""Add phone and summary fields to resume

Revision ID: bd9c37f257a3
Revises: f2d9b9abf890
Create Date: 2025-07-19 11:16:57.117189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd9c37f257a3'
down_revision = 'f2d9b9abf890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_column('summary')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
