"""Initial PostgreSQL migration

Revision ID: f2d9b9abf890
Revises: 
Create Date: 2025-07-19 10:47:55.960841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d9b9abf890'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('certificate', sa.String(length=200), nullable=False),
    sa.Column('certificate_authority', sa.String(length=200), nullable=True),
    sa.Column('not_expired', sa.Boolean(), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('score', sa.String(length=20), nullable=True),
    sa.Column('license_no', sa.String(length=100), nullable=True),
    sa.Column('certificate_url', sa.String(length=500), nullable=True),
    sa.Column('foreign_language', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('is_ctc_sponsor', sa.Boolean(), nullable=True),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('certificate_catalog_id', sa.String(length=36), nullable=True),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=200), nullable=True),
    sa.Column('field_id', sa.String(length=36), nullable=True),
    sa.Column('field', sa.String(length=200), nullable=True),
    sa.Column('sub_field_id', sa.String(length=36), nullable=True),
    sa.Column('sub_field', sa.String(length=200), nullable=True),
    sa.Column('level_id', sa.String(length=36), nullable=True),
    sa.Column('level', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('attendance', sa.Boolean(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=True),
    sa.Column('is_education', sa.Boolean(), nullable=True),
    sa.Column('tech_type', sa.String(length=100), nullable=True),
    sa.Column('reject_reason', sa.String(length=500), nullable=True),
    sa.Column('is_not_has_license_number', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domains',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('school', sa.String(length=200), nullable=False),
    sa.Column('degree', sa.String(length=100), nullable=False),
    sa.Column('major', sa.String(length=100), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('complete_degree', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language_skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('language_id', sa.String(length=36), nullable=False),
    sa.Column('proficiency', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professional_skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('job_title_name', sa.String(length=200), nullable=False),
    sa.Column('experience_month', sa.Integer(), nullable=True),
    sa.Column('experience_year', sa.Integer(), nullable=True),
    sa.Column('job_fill_by_user', sa.String(length=200), nullable=True),
    sa.Column('is_main_skill', sa.Boolean(), nullable=True),
    sa.Column('project_info', sa.JSON(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('resume_project_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('project_key', sa.String(length=100), nullable=True),
    sa.Column('project_code', sa.String(length=100), nullable=True),
    sa.Column('project_rank', sa.String(length=10), nullable=True),
    sa.Column('project_lead', sa.String(length=200), nullable=True),
    sa.Column('project_category', sa.String(length=100), nullable=True),
    sa.Column('customer_code', sa.String(length=100), nullable=True),
    sa.Column('contract_type', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('search_skill', sa.Integer(), nullable=True),
    sa.Column('technology', sa.JSON(), nullable=True),
    sa.Column('project_description', sa.Text(), nullable=True),
    sa.Column('groupname', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('domain', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('pain_points', sa.Text(), nullable=True),
    sa.Column('key_findings', sa.Text(), nullable=True),
    sa.Column('working_process', sa.Text(), nullable=True),
    sa.Column('responsibility', sa.Text(), nullable=True),
    sa.Column('technology_by_pm', sa.String(length=500), nullable=True),
    sa.Column('description_by_pm', sa.Text(), nullable=True),
    sa.Column('is_update_team', sa.Boolean(), nullable=True),
    sa.Column('apply_incompleted', sa.Boolean(), nullable=True),
    sa.Column('skill', sa.String(length=200), nullable=True),
    sa.Column('skill_code', sa.String(length=100), nullable=True),
    sa.Column('seniority', sa.String(length=100), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    op.drop_table('professional_skills')
    op.drop_table('language_skills')
    op.drop_table('education')
    op.drop_table('domains')
    op.drop_table('certificates')
    op.drop_table('resume')
    op.drop_table('languages')
    # ### end Alembic commands ###
